### PR TITLE
Update SnacksLS support

### PR DESCRIPTION
**Pull request by LouisCyfer**
- SnacksLS adjustments (Snacks and Soil have even weight and cost)

### CODE REVIEW

**Comment by allista** [comment]
Yea, but why separate them into a dedicated TankType?

**Comment by LouisCyfer** [comment]
They would have the wrong weights and fill amounts, 1 unit Snacks = 1 Unit Soil and the origin containers from Snacks have the 50/50 or single resource option. Having them separated is a better solution for the mechanics that comes from it, Kerbals can eat random but they always produce 1 Soil for 1 consumed Snack. It also makes management easier to handle, so you can toggle to bring a container Snacks and grab the equal amount Soil after you toggled the container.
Hope this makes sense somehow :D

**Comment by allista** [comment]
Weights may be changed without changing tank types; I understand your reasoning, though. Except that... well, if I would use the same container for both food and what kerbals make from it, I definitely wouldn't want to do it twice, at least without proper cleaning and sterilization and all :rofl: 
Also, I'm not sure Soil resource is used solely by the Snacks mod.

**Comment by LouisCyfer** [comment]
I might be thinking too sci-fy but I can imagine nanites that silently clean up things in background, for the roleplay part. Alternately adding some EC (energy cost) consumption for switching tank type to have a resource cleanup. What do you think?

I assume some change in the dll might be needed but also a possible feature upgrade in future, of course only if you agree.

Thanks for reviewing this patch :)

**Comment by LouisCyfer** [comment]
I assume you don't completely agree to the patch.

**Comment by allista** [comment]
Yep, sorry, but as I said before. Especially considering that current configuration keeps snacks and soil in 1:1 ratio, so no actual rebalancing is needed. Now it's just a spring cleaning of issues and pull requests.

**Comment by LouisCyfer** [comment]
See, this is what I was trying to show by suggesting this patch too. When I add 50% Snacks I cannot add 50% Soil, because Soil has a different weight only for the containers. The containers make them weight different, but as far I read the weight is the same.

**Comment by allista** [comment]
Hm. Didn't get it this time either. Current config uses 1u/L for both Snacks and Soil, tank is configured for 50/50 volume ratio.
Your config uses 0.8u/L also for both resources and the same tank config.
The only thing that is changed is the effective density and the fact that you use the same tank type for both.

**Comment by allista** [comment]
Ah! Now i get it. The useful volume for the food is 0.95, but it's 1 for the soil, yes?

**Comment by LouisCyfer** [comment]
yes, both have the same weight and density. and the tanks are configured for all other LS systems, but Snacks/Soil according to the density, so I made them both 0.8 which matches equivalent snacks-built-in tanks.

**Comment by allista** [comment]
So we need to balance them so that the tank config contains 1:1 in units, not in container volumes.

**Comment by LouisCyfer** [comment]
that I also suggested weeks ago in the KSP forum, but possibly got out of focus.

**Comment by allista** [comment]
So in current configuration this means `Volume=95` for Food and `Volume=100` for Soil in TankConfigs.cfg

**Comment by LouisCyfer** [comment]
I'm pretty sure that you made this because in respect of the other LS systems. would that be an issue to change the food tanks for snacks container only?

E.g.: if snacks is in the container then make volume=100 and the rest of any food-tanks is volume=95 while runtime?

**Comment by allista** [comment]
I mean this config, which is purely for Snacks, nothing else:

```
//by LouisCyfer
TANKCONF:NEEDS[Snacks]
{
    name = Snacks and Soil
```
So don't change anything in tank types, just balance the dedicated tank config.

**Comment by LouisCyfer** [comment]
I see there is no change necessary in tank types, but how to do that without adding a new one?
I'm fine by discarding my suggested patch here if TankConfigs.cfg gets a proper update accoringly.

Thanks :)

**Comment by allista** [comment]
It would be interesting to add resource switching restrictions and some maintenance logic to implement your idea of a food tank that is converted to soil tank. But that's a lot of coding...

**Comment by LouisCyfer** [comment]
sadly I cannot help out there tho .. going on vacation today.

**Comment by allista** [comment]
@LouisCyfer see for yourself in the commit above.

**Comment by LouisCyfer** [comment]
I think this is a good workaround, sorry for my too complicated way.

**Comment by allista** [comment]
Sorry I didn't put enough attention to it before. Glad we've figured it out.

**Pull request closed without merging**
